<a href="https://colab.research.google.com/github/josiemerson/learning_python/blob/master/Testes_Unidade_3_and_4_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pergunta 1** Qual a saída correta para o código a seguir?


In [2]:
import numpy as np
series = [[23, 45, 12, 679], [14, 48, 69, 38]]
new_series = np.array(series)
print(new_series.ndim)
print(new_series.shape)

2
(2, 4)


**Pergunta 2:** Vamos supor que eu queira criar um ndarray de uma dimensão, com 10 posições armazenando o valor 4. Quais das seguintes formas são corretas?

In [3]:
import numpy as np
a = np.zeros(10) + 4
print(a)

a = np.zeros(10) * 4
print(a)

a = np.ones(10) * 4
print(a)

a = np.ones(10) + 4
print(a)

a = np.full(10, 4)
print(a)

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[4 4 4 4 4 4 4 4 4 4]


**Pergunta 3** Qual é a saída correta para o código Python a seguir?

In [4]:
import numpy as np
dataset = np.array(['paul', 'jacob', 'vince', 'paul', 'miky',  'larence', 'warren'])
print(dataset == 'paul')

[ True False False  True False False False]


**Pergunta 4** Qual é a saída para o código a seguir?

In [31]:
import numpy as np
percentiles = [98, 76.37, 55.55, 69, 88]
first_subject = np.array(percentiles)
print(first_subject.dtype.name)
#print(first_subject.dtype)

float64


**Pergunta 5** Quais das opções substituem todos os números pares do array abaixo por -1?

In [28]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[::2] = -1
#arr[1::2] = -1
#arr[arr % 2 == 0] = -1
#d = arr[-2::-2] = -1
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

**Pergunta 6** Após criar uma matriz identidade de 5 x 5, um programador deseja preencher os elementos acima e abaixo da diagonal principal como o número -1. Como ele pode fazer isso?

In [38]:
arr = np.eye(5)
#arr[arr == 0] = -1
#arr[arr != 1] = -1
#arr = np.full((5x5),-1)
#arr = arr - (np.eye(5) + 1)
arr

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

**Atividades Objetiva 04**

**Pergunta 1** Assim como o ndarray do NumPy, os objetos DataFrame e Series do Pandas possuem o atributo shape que é utilizado para verificar e manipular as dimensões dessas estruturas de dados.

In [ ]:
##true (Coloquei errado o correto é false (Não é possível manipular as dimensões do DataFrame e Series atribuindo valores ao shape, como ocorre com o array do NumPy. Portanto a afirmação é falsa.))
## Resposta correta : False

**Pergunta 2** Podemos afirmar que o DataFrame é um grupo de Series que compartilham um mesmo índice, ou seja, cada coluna de um DataFrame nada mais é do que uma Series.

In [ ]:
##false (Um objeto DataFrame é um conjunto de Series.)
##Resposta correta: true

**Pergunta 3** Considere o trecho a seguir:

In [51]:
import pandas as pd
nomes = ("Minas Gerais", "Amazonas", "Maranhão", "Goiás", "Santa Catarina")
siglas = ("MG", "AM", "MA", "GO", "SC")
estados = pd.Series(siglas, nomes)
print(estados.get('Minas Gerais'))
print(estados['Minas Gerais'])

MG
MG


**Pergunta 4** Por Padrão, os métodos do Pandas pr.read_csv e pd.read_excel retornam um objeto DataFrame mesmo que os dados estejam em apenas 1 dimensão. Para alterar esse comportamento, deve-se passar os parâmetro squeeze = True.

In [81]:
import pandas as pd

**Pergunta 5** Suponha que o DataFrame df tenha sido criado conforme o código a seguir:

In [65]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/sandeco/CanalSandeco/master/covid-19/covid_19_data.csv')
#Quais as instruções que podemos utilizar para retornar as primeiras 5 linhas do DataFrame df.
''' Resposta: 
    df.head() e 
    df.head(5)
'''
#df.head() # retorna as primeiras 5 linhas
#df.head(5)# retorna as primeiras 5 linhas
#df.tail() # retorna as ultimas 5 linhas
#df.tail(5)# retorna as ultimas 5 linhas
#df.sample(5) # retorna 5 linhas aleatórias

SNo ObservationDate Province/State  ... Confirmed  Deaths  Recovered
2229  2230      02/24/2020        Ningxia  ...      71.0     0.0       58.0
455    456      01/31/2020          Gansu  ...      29.0     0.0        0.0
2870  2871      03/01/2020            NaN  ...      14.0     0.0        0.0
4528  4529      03/10/2020        Jiangsu  ...     631.0     0.0      627.0
6439  6440      03/18/2020            NaN  ...   35713.0  2978.0     4025.0

[5 rows x 8 columns]

**Pergunta 6** Suponha o DataFrame df possua as colunas A,B,C e D. Marque abaixo as alternativas que **removem** a coluna C (e não apenas retornem o DataFrame sem a coluna) o DataFrame df, deixando apenas as colunas A, B e D.

In [80]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/sandeco/CanalSandeco/master/covid-19/covid_19_data.csv')
#df.drop("Confirmed", axis = 1, inplace= True) #remove a coluna "Confirmed" do df
#df = df.drop("Confirmed", axis = 1) # remove a coluna "Confirmed" do df
#df.drop("Confirmed", axis = 1) #remove a coluna "Confirmed" apenas da visualização do df, mas não dropa do df.
#df.drop("Confirmed", axis = 0, inplace = True) # ocorre exception não encontrou axis 0
df

SNo ObservationDate Province/State  ... Confirmed Deaths  Recovered
0          1      01/22/2020          Anhui  ...       1.0    0.0        0.0
1          2      01/22/2020        Beijing  ...      14.0    0.0        0.0
2          3      01/22/2020      Chongqing  ...       6.0    0.0        0.0
3          4      01/22/2020         Fujian  ...       1.0    0.0        0.0
4          5      01/22/2020          Gansu  ...       0.0    0.0        0.0
...      ...             ...            ...  ...       ...    ...        ...
10353  10354      03/30/2020        Wyoming  ...      94.0    0.0        0.0
10354  10355      03/30/2020       Xinjiang  ...      76.0    3.0       73.0
10355  10356      03/30/2020          Yukon  ...       4.0    0.0        0.0
10356  10357      03/30/2020         Yunnan  ...     180.0    2.0      172.0
10357  10358      03/30/2020       Zhejiang  ...    1255.0    1.0     1225.0

[10358 rows x 8 columns]